CREATE TABLE MSI_PRODUCT (
ID NUMBER(10,0) NOT NULL AUTO_INCREMENT,
NAME VARCHAR2(255) DEFAULT NULL,
BRAND VARCHAR2(255) DEFAULT NULL,
PRICE NUMBER DEFAULT NULL,
STOCK NUMBER DEFAULT NULL,
IMAGE VARCHAR2(255) DEFAULT NULL,
PRIMARY KEY (ID));

CREATE SEQUENCE MSI_PRODUCT_SEQ;